### ISSUE TITLE
Support for Huin H430P

### ISSUE THREAD

**Issue by respi02** [joseluis/huion-linux-drivers#16]
Hello i would to ask you, if you can add support for Huion H430P :)

/edit forgot console output
https://pastebin.com/8CpkRs9M

**Comment by joseluis** [comment]
Hi @SandBoxCZ, I've added `[tablet_h430p]`, please try it and let me know if it works for you.

If it doesn't work for you, I'll ask you to either set `debug_mode = true` or  `current_tablet = [tablet_debug]` again), then go through the suggested *corner touching* routine and copy&paste the output back to me to do some checking on that data.

**Comment by respi02** [comment]
Hi, it does not work, so im sending you the requested data.

https://pastebin.com/637iX7LL

Hope this log helps fix it :)

**Comment by joseluis** [comment]
I've updated the script with better debug info. Please use the latest version (of script and config) and leave everything by default, except for your chose tablet in the config.ini file:

```
current_tablet = [tablet_h430p]
```

thanks!

**Comment by respi02** [comment]
Here is debug info.

https://pastebin.com/AyJYtaVP

Hope this helps you more :)

**Comment by joseluis** [comment]
Hey, thank you for the info. But I still don't know how to make it work. I'll keep working on it, but for now I recommend you to use [latest release of digimend kernel drivers](https://github.com/DIGImend/digimend-kernel-drivers/releases), it added support to your tablet in version V8

**Comment by joseluis** [comment]
Hi again, you can also try running this small script, in the colment I link below, which performs a basic test, to rule out a system malfunction, like in the linked issue, similar to yours:

https://github.com/joseluis/huion-linux-drivers/issues/17#issuecomment-480206333
