### ISSUE TITLE
Error: uclogic-probe not found [GT-191]

### ISSUE THREAD

**Issue by wrightwriter** [joseluis/huion-linux-drivers#19]
This is the output I get. it's weird, because uclogic-probe works from terminal if called with ```uclogic-probe```, but this driver tries to find it in  ```/usr/local/bin/```, where it's not.

```
Finding USB device. . . Done!
grabbed interface %d 0
grabbed interface %d 1
Reading configuration. . . Done!
hid_uclogic            16384  0
/bin/sh: 1: /usr/local/bin/uclogic-probe: not found
/bin/sh: 1: /usr/local/bin/uclogic-decode: not found
Preparing driver. . . ERROR running the following comand:
	"/usr/local/bin/uclogic-probe" "3" "5" | "/usr/local/bin/uclogic-decode"
RETURN CODE: 127
 
```

EDIT: FIX IS TO INSTALL uclogic like intstructions in main repo

**Comment by joseluis** [comment]
Correct. And you can also change its path in `config.ini` which by default is `uclogic_bins = /usr/local/bin`
