### ISSUE TITLE
Failure to start in ubuntu 19.04

### ISSUE THREAD

**Issue by DavidBM** [joseluis/huion-linux-drivers#20]
Hi! 

I had the driver working wonderfully in Ubuntu 18.10. Once I updated to 19.04 it stoped working with this Error:

```
Finding USB device. . . Done!
Reading configuration. . . Done!
Preparing driver. . . Done!
Setting up driver. . . Done!
	Tablet model name         GT-191
	Buttons                   disabled (0)
	Scrollbar                 disabled (0)
	Notifications:            ENABLED
		for buttons       ENABLED
		for scrollbar     disabled
	Screen                    Enabled (1920x1080)
	Current Monitor Setup     [monitor_3]
	Multi Monitor Setup       ENABLED
	Calling xrandr            ENABLED

Setting up multiple monitors. . . 
Running xrandr. . . 
Traceback (most recent call last):
  File "./huion-tablet-driver.py", line 743, in <module>
    main.run()
  File "./huion-tablet-driver.py", line 33, in run
    multi_monitor()
  File "./huion-tablet-driver.py", line 223, in multi_monitor
    cmd='xrandr {}'.format(main.settings['xrandr_args'])
KeyError: 'xrandr_args'
```

I traced back the error to the line 663: 
`        main.settings['total_screen_width'] = ast.literal_eval(config.get(current_monitor_setup,
            'total_screen_width').split("#",1)[0].strip())`

I tested a bit and seems that `ast.literal_eval` fails to eval the string "2560 + 2560 + 1920". I researched a bit and seems that literal_eval shouln't eval expressions bit it was doing it because of compatibility reasons. (https://stackoverflow.com/questions/40584417/why-does-ast-literal-eval5-7-fail)

I changed it to a normal (and more dangerous) eval and it works now. I wond't suggest to use `eval` in a driver that runs with sudo, but maybe you can find another way to make the maths there. I'm not an expert in python.

**Comment by joseluis** [comment]
Thank you very much for the thorough investigation.

I found the module [numexpr](https://github.com/pydata/numexpr) is probably the best option for safely parsing algebraic expressions, and it's already present in major distributions repositories.

So I've replaced all calls to `ast.literal_eval` for calls to `numexpr.evaluate`, and it seems to works well.

You'll have to install the additional dependency (`sudo apt install python3-numexpr`) and then it should work just fine using the last version of the script.
