### ISSUE TITLE
Python3 hogging CPU

### ISSUE THREAD

**Issue by triantares** [joseluis/huion-linux-drivers#26]
When shutting off my gt133 (on Elive 3.7.9 using Debian Buster) with the on/off button python3 hogs up to 100% of 1 CPU making CPU temperature rise. Hitting \<Ctrl and c\> solves the case but this should not be happening.

**Comment by yayfortrees** [comment]
This is fixed by exiting on disconnect #36

**Comment by triantares** [comment]
Kudos !!Your commit worked perfectly.
Issue resolved, thanks.

**Comment by joseluis** [comment]
Fantastic. I've merged the linked PR.
