### ISSUE TITLE
xinput list --short | grep "Tablet Monitor Pen" RETURN CODE: 1

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [joseluis/huion-linux-drivers#63]
What's this error?
Unable to connect to X server
ERROR running the following comand:
        xinput list --short | grep "Tablet Monitor Pen"
RETURN CODE: 1

**Comment by IllDrakon** [comment]
I have the same issues
//Ubuntu 18.04, var Kubuntu

**Comment by jaakkonakaza** [comment]
Does `sudo DISPLAY=$DISPLAY ./huion-tablet-driver.py` give the same error? Also if that doesn't work try running `xhost local:root`

**Comment by GreatBigWhiteWorld** [comment]
Sorry I had to return the tablet and bought a wacom tablet instead.
