### ISSUE TITLE
Make the screen tablet variable less ambiguous, or remove it entirely (plus new tablet settings for the h610prov2)

### ISSUE THREAD

**Issue by cabinboy1031** [joseluis/huion-linux-drivers#64]
After a long while of debugging trying to get my h610prov2 to work on only one screen i found out that the 'screen' variable turns /on/ the xinput mapping i wanted instead of what i assumed meant turns /off/

I assumed this because i would imagine a cintiq would have its own screen mappings instead of needing the ones that linux provided. Screen = true meaning that a tablet has a screen of its own.

I only found out that it turns /on/ xinput mapping after going through the code and finding out that the log saying that it started doesnt actually show up, im glad for the extensive debugging that happens too else i doubt i would ever have found this, but i wish for 'screen' to either be removed or made a bit less ambiguous so others might have a better time adding their tablets.

Either way here are the settings i use for my tablet to add to the config file:
```[tablet_h610pro2]
model_name = H610 PRO
screen = true
pen_max_x = 50800
pen_max_y = 31750
pen_max_z = 8191
resolution = 5080
buttons = 8
```

**Comment by joseluis** [comment]
Thank you for the info! I'll rethink the screen part
