### ISSUE TITLE
Xinput error 1060Plus. Ubuntu 20.04

### ISSUE THREAD

**Issue by climent1** [joseluis/huion-linux-drivers#78]
Hi! after installation I get the next error in "xinput" when sudo ./huion-tablet-driver.py

VPEN:
name "Tablet Monitor Pen 210950", bus "BUS_USB", vendor "0001", product "0001", version "0003", phys "py-evdev-uinput"
event types: EV_SYN EV_KEY EV_ABS

XINPUT:
ERROR running the following comand:
	xinput list --short | grep "Tablet Monitor Pen"

**Comment by joseluis** [comment]
Unfortunately there are bugs that appeared in recent versions of linux distributions, between different versions of python that are complicated to sort out.

I'm currently recreating the software in Rust, and the bugs will all be addressed in this new version.

**Comment by climent1** [comment]
thanks a lot. I will be watching the news
